# Generated by Django 5.1.1 on 2024-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='addressDetails',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workExperience',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phoneNo',
            new_name='phone_no',
        ),
        migrations.AddField(
            model_name='employee',
            name='address_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
